FROM golang:1.23-alpine AS base

ENV GO111MODULE="on"
ENV GOOS="linux"
ENV CGO_ENABLED=1

# System dependencies
RUN apk update && apk add --no-cache ca-certificates curl bash gcc libc-dev librdkafka-dev
RUN go install -tags musl gotest.tools/gotestsum@latest
RUN go install -tags musl github.com/golang/mock/mockgen@v1.6.0
RUN go install -tags musl github.com/smartystreets/goconvey@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

ARG PROJECT_NAME="app"
ARG VERSION="dev"
ARG COMMIT="none"
ENV CGO_ENABLED=1
ENV GOPROXY=https://proxy.golang.org

FROM base AS dev
WORKDIR /app

COPY . .

RUN go mod download

# Configure to use dynamic librdkafka instead of static
ENV CGO_LDFLAGS="-lrdkafka"
ENV CGO_CFLAGS="-I/usr/include/librdkafka"
ENV KAFKA_USE_DYNAMIC_LINKING=1

RUN go install -tags musl github.com/go-delve/delve/cmd/dlv@latest

# Hot reloading mod
RUN go get -tags musl -u github.com/air-verse/air@v1.61.7 && go install -tags musl github.com/go-delve/delve/cmd/dlv@latest
RUN go install -tags musl github.com/air-verse/air@v1.61.7

EXPOSE 8080
EXPOSE 2345

ENTRYPOINT ["/go/bin/air"]
