// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/user (interfaces: IUsecaseUser)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_usecase_user.go -package=mocks app/usecase/user IUsecaseUser
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIUsecaseUser is a mock of IUsecaseUser interface.
type MockIUsecaseUser struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseUserMockRecorder
	isgomock struct{}
}

// MockIUsecaseUserMockRecorder is the mock recorder for MockIUsecaseUser.
type MockIUsecaseUserMockRecorder struct {
	mock *MockIUsecaseUser
}

// NewMockIUsecaseUser creates a new mock instance.
func NewMockIUsecaseUser(ctrl *gomock.Controller) *MockIUsecaseUser {
	mock := &MockIUsecaseUser{ctrl: ctrl}
	mock.recorder = &MockIUsecaseUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecaseUser) EXPECT() *MockIUsecaseUserMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUsecaseUser) Create(user *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUsecaseUserMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUsecaseUser)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockIUsecaseUser) Delete(user *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIUsecaseUserMockRecorder) Delete(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUsecaseUser)(nil).Delete), user)
}

// GetUser mocks base method.
func (m *MockIUsecaseUser) GetUser(id int) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", id)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIUsecaseUserMockRecorder) GetUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUser), id)
}

// GetUserByToken mocks base method.
func (m *MockIUsecaseUser) GetUserByToken(token string) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByToken", token)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByToken indicates an expected call of GetUserByToken.
func (mr *MockIUsecaseUserMockRecorder) GetUserByToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByToken", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUserByToken), token)
}

// GetUsers mocks base method.
func (m *MockIUsecaseUser) GetUsers(filters entity.EntityUserFilters) ([]entity.EntityUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", filters)
	ret0, _ := ret[0].([]entity.EntityUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIUsecaseUserMockRecorder) GetUsers(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUsers), filters)
}

// GetUsersFromIDs mocks base method.
func (m *MockIUsecaseUser) GetUsersFromIDs(ids []int) ([]entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFromIDs", ids)
	ret0, _ := ret[0].([]entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFromIDs indicates an expected call of GetUsersFromIDs.
func (mr *MockIUsecaseUserMockRecorder) GetUsersFromIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFromIDs", reflect.TypeOf((*MockIUsecaseUser)(nil).GetUsersFromIDs), ids)
}

// LoginUser mocks base method.
func (m *MockIUsecaseUser) LoginUser(email, password string) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", email, password)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockIUsecaseUserMockRecorder) LoginUser(email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockIUsecaseUser)(nil).LoginUser), email, password)
}

// Update mocks base method.
func (m *MockIUsecaseUser) Update(user *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIUsecaseUserMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUsecaseUser)(nil).Update), user)
}

// UpdatePassword mocks base method.
func (m *MockIUsecaseUser) UpdatePassword(id int, oldPassword, newPassword, confirmPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", id, oldPassword, newPassword, confirmPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIUsecaseUserMockRecorder) UpdatePassword(id, oldPassword, newPassword, confirmPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIUsecaseUser)(nil).UpdatePassword), id, oldPassword, newPassword, confirmPassword)
}
