// Code generated by MockGen. DO NOT EDIT.
// Source: app/usecase/user (interfaces: IRepositoryUser)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_usecase_repository_user.go -package=mocks app/usecase/user IRepositoryUser
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "app/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRepositoryUser is a mock of IRepositoryUser interface.
type MockIRepositoryUser struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryUserMockRecorder
	isgomock struct{}
}

// MockIRepositoryUserMockRecorder is the mock recorder for MockIRepositoryUser.
type MockIRepositoryUserMockRecorder struct {
	mock *MockIRepositoryUser
}

// NewMockIRepositoryUser creates a new mock instance.
func NewMockIRepositoryUser(ctrl *gomock.Controller) *MockIRepositoryUser {
	mock := &MockIRepositoryUser{ctrl: ctrl}
	mock.recorder = &MockIRepositoryUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepositoryUser) EXPECT() *MockIRepositoryUserMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIRepositoryUser) CreateUser(user *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIRepositoryUserMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIRepositoryUser)(nil).CreateUser), user)
}

// DeleteUser mocks base method.
func (m *MockIRepositoryUser) DeleteUser(user *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIRepositoryUserMockRecorder) DeleteUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIRepositoryUser)(nil).DeleteUser), user)
}

// GetByID mocks base method.
func (m *MockIRepositoryUser) GetByID(id int) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIRepositoryUserMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIRepositoryUser)(nil).GetByID), id)
}

// GetByMail mocks base method.
func (m *MockIRepositoryUser) GetByMail(email string) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMail", email)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMail indicates an expected call of GetByMail.
func (mr *MockIRepositoryUserMockRecorder) GetByMail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMail", reflect.TypeOf((*MockIRepositoryUser)(nil).GetByMail), email)
}

// GetUser mocks base method.
func (m *MockIRepositoryUser) GetUser(id int) (*entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", id)
	ret0, _ := ret[0].(*entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIRepositoryUserMockRecorder) GetUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIRepositoryUser)(nil).GetUser), id)
}

// GetUsers mocks base method.
func (m *MockIRepositoryUser) GetUsers(filters entity.EntityUserFilters) ([]entity.EntityUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", filters)
	ret0, _ := ret[0].([]entity.EntityUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIRepositoryUserMockRecorder) GetUsers(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIRepositoryUser)(nil).GetUsers), filters)
}

// GetUsersFromIDs mocks base method.
func (m *MockIRepositoryUser) GetUsersFromIDs(ids []int) ([]entity.EntityUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersFromIDs", ids)
	ret0, _ := ret[0].([]entity.EntityUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersFromIDs indicates an expected call of GetUsersFromIDs.
func (mr *MockIRepositoryUserMockRecorder) GetUsersFromIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersFromIDs", reflect.TypeOf((*MockIRepositoryUser)(nil).GetUsersFromIDs), ids)
}

// UpdateUser mocks base method.
func (m *MockIRepositoryUser) UpdateUser(user *entity.EntityUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockIRepositoryUserMockRecorder) UpdateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockIRepositoryUser)(nil).UpdateUser), user)
}
